/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define USART3_IRQNO 39

int main(void)
{
//	Manually pend the interrupt in the interrupt status pending register (NVIC).
	uint32_t *pISPR;
	pISPR = (uint32_t*)0XE000E204; // ISPR1
	*pISPR |= (1 << (USART3_IRQNO % 32));

//	Set the interrupt set enable register for that particular interrupt.
	uint32_t *pISER;
	pISER = (uint32_t*)0xE000E104; // ISER1
	*pISER |= (1 << (USART3_IRQNO % 32));

    /* Loop forever */
	for(;;);
}

// ISR USART3_IRQHandler
void USART3_IRQHandler(void) {
	printf("\n In USART3 ISR.\n");
}


