/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#define ALIAS_BASE		0x22000000
#define BIT_BAND_BASE	0x20000000

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    uint8_t *ptr = (uint8_t*) 0x20000200;
    *ptr = 0xFF;							// assigning 0xFF
    *ptr &= ~(1 << 7);							// 0 at 7th bit
    uint8_t *alias_addrs = ALIAS_BASE + (32*(0x20000200 - BIT_BAND_BASE)) + 7*4;	// call alias addrs for bit banding
    *ptr = 0xFF;		// Resetting the pointer
    *alias_addrs = 0;	// changing the it at 7th position to 0
	for(;;);
}
